---
- name: Update python-apt
  sudo: true
  command: apt-get install python-apt -y

- name: Update python-pycurl
  sudo: true
  command: apt-get install python-pycurl -y

- name: Add the Neo4j apt key
  apt_key: url=http://debian.neo4j.org/neotechnology.gpg.key state=present

- name: Setup Neo4j repository
  apt_repository: repo="deb http://debian.neo4j.org/repo stable/" state=present update_cache=yes

- name: Check Neo4j package is installed
  apt: pkg={{ neo4j_package }}={{ neo4j_package_version }} state=present

- name: Ensure graph DB folder exists
  file: path={{ neo4j_server_database_location }} state=directory owner=neo4j group=adm mode=0755

- name: Add logrotate configuration
  copy: src=neo4j.logrotate dest=/etc/logrotate.d/neo4j owner=root group=root mode=0640