---
- name: Include installation
  include: install.yml

- name: Remove old auth/roles pre-configured
  shell: rm -rf /var/lib/neo4j/data/dbms/*

- name: Configure neo4j-admin
  shell: neo4j-admin set-initial-password {{ neo4j_admin_password }}

- name: Configure Neo4j conf
  template: src=neo4j.conf.j2 dest=/etc/neo4j/neo4j.conf owner=neo4j group=adm mode=0644
  notify: Restart neo4j

- name: Ensure open files soft limit is set
  lineinfile: dest=/etc/security/limits.conf regexp="^neo4j\s+soft" line="neo4j   soft    nofile  40000" insertbefore="# End of file" state=present

- name: Ensure open files hard limit is set
  lineinfile: dest=/etc/security/limits.conf regexp="^neo4j\s+hard" line="neo4j   hard    nofile  40000" insertbefore="# End of file" state=present

- name: Ensure limits are enabled
  lineinfile: dest=/etc/pam.d/su  regexp="^(# )?session    required   pam_limits.so" line="session    required   pam_limits.so" state=present
  notify: Reboot

- name: Setting /etc/neo4j/jmx.password attributes
  file: name=/etc/neo4j/jmx.password mode=0600
  notify: Restart neo4j

- name: Downloading plugins
  get_url: url={{ item.url }} dest=/var/lib/neo4j/plugins/{{ item.filename }} owner=neo4j group=adm
  with_items: "{{ neo4j_plugins }}"
  notify: Restart neo4j

- name: Ensure Neo4j service is enabled and restarted
  service: name=neo4j enabled=yes state=restarted